a = input("Digite algo:")
print("O tipoprimitivo desse valor é ",type(a))
print("Só tem espaço?", a.isspace())
print("É um número?", a.isnumeric())
print("É alfanúmerico?", a.isalnum())
print("É alfabetico?", a.isalpha())
print("Está em maiuscula?", a.isupper())
print("Está em minuscula?", a.islower())
print("Está capitalizada?", a.istitle())
